apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  namespace: dev
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c','echo "Initializing..."; sleep 5']
      containers:
      - name: deploy
        image: dockerghana1/hello-world
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

