apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matachLabels:
      app: node-exporter
    template:
      metadata:
        labels:
          app: node-exporter
      spec:
        containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.1
          imagePullPolicy: Always
          args:
            - '-path.rootfs=/host'  # Required for EKS and containerized hosts
          ports:
          - name: metrics
            containerPort: 9100
            hostPort: 9100
          volumeMounts:
          - name: root
            mountPath: /host
            readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumes:
          - name: root
            hostPath:
              path: /
              type: Directory
            
